# Generated by Django 4.1.3 on 2022-11-06 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formfillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('dept_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('provost_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('register_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('student_id', models.CharField(max_length=200, verbose_name='Student ID')),
                ('session', models.CharField(max_length=50, verbose_name='session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
